# Generated by Django 3.2.8 on 2021-11-10 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DB', '0002_result'),
    ]

    operations = [
        migrations.CreateModel(
            name='fifteen_min',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(max_length=30)),
                ('open', models.FloatField()),
                ('high', models.FloatField()),
                ('low', models.FloatField()),
                ('close', models.FloatField()),
            ],
        ),
        migrations.RemoveField(
            model_name='four_hours',
            name='Volume',
        ),
        migrations.RemoveField(
            model_name='one_day',
            name='Volume',
        ),
        migrations.RemoveField(
            model_name='one_hour',
            name='Volume',
        ),
    ]
